# These are supported funding model platforms

github: Eratonos # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Eratonos # Replace with a single Patreon username
open_collective: Eratonos # Replace with a single Open Collective username
ko_fi: Eratonos # Replace with a single Ko-fi username
tidelift: Eratonos # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: Eratonos # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Eratonos # Replace with a single Liberapay username
issuehunt: Eratonos # Replace with a single IssueHunt username
otechie: Eratonos # Replace with a single Otechie username
lfx_crowdfunding: Eratonos # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: Eratonos # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
